CREATE TABLE IF NOT EXISTS USERS (
	ID UUID PRIMARY KEY,
	-- AUTHENTICATION & AUTHORIZATION
	EMAIL TEXT UNIQUE NOT NULL,
	HASH TEXT NOT NULL,
	ROLE USER_ROLE NOT NULL DEFAULT 'user',
	-- PASSWORD RESET
	PASSWORD_OTP TEXT,
	PASSWORD_OTP_EXPIRY TIMESTAMPTZ,
	PASSWORD_RESET_ATTEMPTS INT NOT NULL DEFAULT 3,
	-- PROFILE
	FIRST_NAME TEXT,
	MIDDLE_NAME TEXT,
	LAST_NAME TEXT,
	DATE_OF_BIRTH DATE,
	SEX USER_SEX,
	PHONE TEXT UNIQUE,
	COUNTRY TEXT,
	AVATAR_URL TEXT,
	-- META
	VERIFIED BOOLEAN DEFAULT FALSE,
	CREATED TIMESTAMPTZ DEFAULT NOW(),
	UPDATED TIMESTAMPTZ DEFAULT NOW()
);